apiVersion: v1   #Define the version of which object bekings to.
kind: Pod        #Define Object that is pod
metadata:
  name: nginx-pod # name of the pod
  labels:         #tags given to the pod or filter purpose
    app: nginx
spec:             #define the container configuration.
  containers:
  - name: nginx-container  #name to the container
    image: nginx   #name of the image
